# Generated by Django 5.1.4 on 2025-03-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
                ('team_id', models.IntegerField(null=True)),
            ],
        ),
    ]
