# Generated by Django 5.1.4 on 2025-03-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0004_alter_playericon_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
