# Generated by Django 5.1.4 on 2025-03-18 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
